Reason mode cleanup and refactoring
reasonml-editor/reason-mode pull request #1
Opened 2017-05-19 08:25 UTC by fredyr

- Removed the remains of the rust mode origins
- Moved the utop integration into reason-interaction.el
- Indentation support moved into reason-indent
- First JSX syntax support
- Boolean constanst true/false highlighted as constants instead of keywords
- Added missing keywords: external/mutable/where/open

2017-05-19 16:46 UTC, arichiardi requested changes

2017-05-19 16:46 UTC, arichiardi commented on reason-mode.el
> -;;; Commentary:
Oh I spent a full 10 minutes to write this and now it goes away? Can we restore it?

2017-05-19 16:46 UTC, arichiardi commented on reason-interaction.el
> +
Probably we need to add the header like in `reason-mode.el` in all files (or my emacs complains):

```
;;; reason-mode.el --- A major emacs mode for editing Reason (based on rust-mode) -*-lexical-binding: t-*-
  ;; Portions Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
```

2017-05-19 16:46 UTC, arichiardi commented on reason-indent.el
> +(defcustom reason-indent-offset 2
Can we add the header? See other comment.

2017-05-19 16:46 UTC, arichiardi commented on reason-mode.el
>  (require 'refmt)
Let's keep the `require` on the top. Not that it matters, but I feel it is better to see what it is loaded up there.

2017-05-19 16:46 UTC, arichiardi commented on reason-indent.el
> +at the beginning of the defun body.
Shall we error out or handle the case this is not the case?

2017-05-19 16:46 UTC, arichiardi commented on reason-mode.el
> +;;; TODO: keymaps, e.g. (define-key map "\C-c\C-a" 'reason-mode-find-alternate-file)
definitely

2017-05-19 17:27 UTC, fredyr commented on reason-mode.el
> -;;; Commentary:
My bad.

2017-05-19 17:30 UTC, fredyr commented on reason-indent.el
> +at the beginning of the defun body.
reason-indent is just the indent parts pulled out of reason-mode.  these functions are as in the current version. sounds good to improve this as things progress, but for now i wouldn't now how.

2017-05-19 17:33 UTC, arichiardi commented on reason-indent.el
> +at the beginning of the defun body.
Yeah for sure, I thought it was added brand new ;)

2017-05-19 17:47 UTC, fredyr commented
I've updated as per your requests. Let me know if there's anything else.

2017-05-19 17:51 UTC, arichiardi commented
Awesome thanks, will try it out and merge when ready, good job!

2017-05-24 02:13 UTC, arichiardi approved these changes

2017-05-24 02:21 UTC, merged